/**
 * מסנכרן shared/halakha.json → netlify/functions/_halakhaData.mjs
 * (Metro מייבא JSON ישירות; Netlify functions מקבלים עותק .mjs)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'shared', 'halakha.json');
const dest = join(root, 'netlify', 'functions', '_halakhaData.mjs');

const json = readFileSync(src, 'utf8');
JSON.parse(json); // validate
const out = `/** Generated by scripts/sync-halakha.mjs — do not edit by hand. */\nexport default ${json.trim()};\n`;
writeFileSync(dest, out, 'utf8');
console.log('synced', dest);
